"""
LLM Report Generator — Neuratia Phase 6

Builds a structured clinical summary prompt from the patient's fusion result,
retrieves relevant literature context via TF-IDF RAG, and calls the Google
Gemini API (free tier via google-generativeai / AI Studio key).

Framing rules (mandatory, per project-rules.md):
1. Every generated report MUST include a non-diagnostic disclaimer.
2. Score must be labelled as "Unvalidated Fusion Score — Research Prototype".
3. No definitive clinical conclusions. Report tone = "warrants further evaluation".
4. Fallback to template report if Gemini API is unavailable (placeholder key).
"""

from __future__ import annotations

import os
from typing import Any

from app.services.rag_retrieval import RAGRetriever

_retriever = RAGRetriever()

DISCLAIMER = (
    "⚠ IMPORTANT — NON-DIAGNOSTIC DISCLAIMER: This report is generated by a "
    "research prototype AI system (Neuratia). It is NOT a clinical diagnosis, "
    "NOT a certified medical device output, and does NOT constitute medical "
    "advice. All results should be reviewed by a qualified neurologist or "
    "clinician before any clinical interpretation or action."
)


def _build_prompt(fusion_result: dict[str, Any], rag_chunks: list[dict]) -> str:
    composite = fusion_result.get("composite_score", "N/A")
    risk_band = fusion_result.get("risk_band", "unknown")
    risk_label = fusion_result.get("risk_label", "")
    contributions = fusion_result.get("modality_contributions", {})
    missing = fusion_result.get("missing_modalities", [])

    contrib_lines = "\n".join(
        f"  - {k.capitalize()}: {round(v * 100)}% contribution"
        for k, v in contributions.items()
    )
    missing_note = (
        f"Note: {', '.join(missing)} modality data was unavailable; "
        "weights were redistributed proportionally."
        if missing else "All three modalities were captured."
    )

    rag_context = "\n\n".join(
        f"[{c['topic']}]\n{c['content']}" for c in rag_chunks
    )

    return f"""You are a clinical AI assistant for a research screening tool called Neuratia.
Your task is to write a structured, evidence-based screening summary for a clinician to review.

MANDATORY CONSTRAINTS:
- Begin with the disclaimer below verbatim.
- Never state a definitive diagnosis. Use "warrants further evaluation" language.
- Reference only the provided evidence context. Do not invent citations.
- Keep the report under 400 words.
- Use plain English that both clinicians and informed patients can understand.
- End with a clear "Next Steps" section recommending clinician follow-up.

DISCLAIMER (include verbatim at top):
{DISCLAIMER}

---

PATIENT SCREENING SUMMARY DATA:
Composite Risk Score: {composite} ({int(composite * 100) if composite else 'N/A'}%)
Risk Band: {risk_band.upper()} — {risk_label}

Modality Contributions:
{contrib_lines}

{missing_note}

---

RELEVANT EVIDENCE CONTEXT (from peer-reviewed literature):
{rag_context}

---

Write the clinical screening summary report now. Structure it as:
1. Executive Summary (2–3 sentences)
2. Modality Findings (one paragraph per available modality)
3. Evidence Context (cite the retrieved literature)
4. Next Steps (bullet list)
5. Disclaimer (verbatim from above)
"""


def generate_report(fusion_result: dict[str, Any]) -> dict[str, Any]:
    """
    Generates a RAG-augmented LLM clinical summary for a session's fusion result.
    Falls back to a structured template report if Gemini API key is a placeholder.
    """
    risk_band = fusion_result.get("risk_band", "moderate")
    query = (
        f"{risk_band} cognitive risk speech gaze digit span "
        f"{'antisaccade' if 'gaze' in fusion_result.get('modality_contributions', {}) else ''} "
        f"MCI Alzheimer screening"
    )
    rag_chunks = _retriever.retrieve(query, top_k=3)

    gemini_key = os.environ.get("GEMINI_API_KEY", "")
    is_placeholder = not gemini_key or gemini_key.startswith("placeholder")

    if is_placeholder:
        return _template_report(fusion_result, rag_chunks)

    try:
        import google.generativeai as genai

        genai.configure(api_key=gemini_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = _build_prompt(fusion_result, rag_chunks)
        response = model.generate_content(prompt)
        report_text = response.text

        return {
            "report_text": report_text,
            "rag_chunks_used": rag_chunks,
            "model": "gemini-1.5-flash",
            "is_demo_mode": False,
            "disclaimer": DISCLAIMER,
        }
    except Exception as e:
        print(f"[ReportGenerator] Gemini API notice: {e!s}")
        return _template_report(fusion_result, rag_chunks)


def _template_report(
    fusion_result: dict[str, Any], rag_chunks: list[dict]
) -> dict[str, Any]:
    """
    Structured template report for demo/fallback mode when Gemini is unavailable.
    Preserves correct framing and citations even without live LLM.
    """
    composite = fusion_result.get("composite_score", 0.5)
    risk_band = fusion_result.get("risk_band", "moderate")
    risk_label = fusion_result.get("risk_label", "Moderate Risk Signal")
    contributions = fusion_result.get("modality_contributions", {})
    missing = fusion_result.get("missing_modalities", [])

    pct = int((composite or 0.5) * 100)

    modality_lines = []
    if "speech" in contributions:
        modality_lines.append(
            f"**Speech/Linguistic:** Contribution {round(contributions['speech'] * 100)}% "
            "— Acoustic and linguistic features were extracted. Reduced type-token ratio "
            "and elevated filler word rate are early markers of word-retrieval difficulty "
            "(Fraser et al. 2016)."
        )
    if "gaze" in contributions:
        modality_lines.append(
            f"**Gaze/Oculomotor:** Contribution {round(contributions['gaze'] * 100)}% "
            "— Antisaccade error rate, fixation dispersion, and saccadic latency were "
            "evaluated against published norms (Antoniades 2013; Holmqvist 2011)."
        )
    if "cognitive" in contributions:
        modality_lines.append(
            f"**Cognitive Games:** Contribution {round(contributions['cognitive'] * 100)}% "
            "— Digit span performance was normalised against age and education band "
            "using WAIS-IV norms (Monaco et al. 2013)."
        )

    missing_note = (
        f"\n\n*Note: {', '.join(missing)} modality data was unavailable and "
        "its weight was redistributed.*" if missing else ""
    )

    report_text = f"""{DISCLAIMER}

---

**Composite Risk Score:** {pct}% — {risk_label}
**Report Mode:** Template (Demo — Gemini API key not configured)

This research prototype screening session produced a composite oculomotor, speech, and
cognitive risk score of **{pct}%**, classified as **{risk_band.upper()} RISK SIGNAL**.
This result {
    "warrants prompt clinician review and comprehensive neuropsychological evaluation."
    if risk_band == "high" else
    "warrants clinician follow-up to rule out early cognitive changes."
    if risk_band == "moderate" else
    "is within the expected range; routine monitoring is recommended."
}

{chr(10).join(modality_lines)}{missing_note}

{'; '.join(c['topic'] for c in rag_chunks)} — evidence retrieved from the Neuratia
reference corpus (Fraser 2016, Luz 2021, Antoniades 2013, Holmqvist 2011, Monaco 2013).

- **Share this report with a qualified neurologist or geriatric psychiatrist.**
- A formal neuropsychological assessment (MoCA, MMSE, or full WAIS-IV battery) is recommended.
- Review current medications, sleep quality, and mood — all can temporarily affect screening scores.
- Repeat the Neuratia screening in 3–6 months to monitor trends.
- Do NOT use this report as the sole basis for any clinical or personal decision.
"""

    return {
        "report_text": report_text,
        "rag_chunks_used": rag_chunks,
        "model": "template_fallback",
        "is_demo_mode": True,
        "disclaimer": DISCLAIMER,
    }
